server:
 port: 8888
spring:
 application:
    name: configServer
 cloud: 
  config: 
   server: 
    git:
     username: 49917747@qq.com
     password: 394684950a
     uri: https://github.com/wind3/VIGALYN-CONFIG
eureka: 
  instance:
    hostname: configServer-instance-01
  client:
    service-url: 
     defaultZone: http://localhost:8080/eureka/

      
    