server:
 port: 8887
spring:
 application:
    name: configServer
 cloud: 
  config: 
   server: 
    git:
     uri: https://github.com/wind3/VIGALYN-CONFIG
     searchPaths: vigalyn-ms-www
eureka: 
  instance:
    hostname: localhost
    appname: configServer
  client:
    service-url: 
     defaultZone: http://localhost:8080/eureka/

      
    